services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: qna
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d qna']
      interval: 2s
      timeout: 3s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    command: >
      bash -lc 'python scripts/wait_for_db.py &&
                python manage.py migrate &&
                gunicorn qna.wsgi:application --bind 0.0.0.0:8000 --workers 2'
    restart: unless-stopped

volumes:
  pgdata:
